---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /usr/sbin/init
  require_chef_omnibus: false
  forward:
    - 8081:8081

provisioner:
  name: chef_zero

transport:
  username: kitchen

platforms:
  - name: centos
    driver_config:
      image: "centos_chef_omnibus:latest"
      platform: "centos"
    # driver_config:
    #   dockerfile: test/Dockerfile
    #   privileged: true # Needed by systemd to access cgroups
    #   run_command: /usr/sbin/init # Start systemd as root process
    #   use_sudo: false
    #   ssh_key: ~/.ssh/id_rsa

suites:
  - name: default
    run_list:
      - recipe[demo::default]
  - name: mytest
    run_list:
      - recipe[mytest]
