LineLength:
  Max: 500

HashSyntax:
  EnforcedStyle: hash_rockets

SpaceBeforeFirstArg:
  Exclude:
    - "**/metadata.rb"

AllCops:
  Exclude:
    - "Vagrantfile"
    - "Thorfile"
    - "Guardfile"
    - "Berksfile"
    - ".kitchen/**"
    - test/**/*
